tests/test-image: Fail in the absence of the file list
Signed-off-by: Gleb Fotengauer-Malinovskiy <glebfm@altlinux.org>

diff --git a/tests/test-image b/tests/test-image
--- a/tests/test-image
+++ b/tests/test-image
@@ -155,11 +155,12 @@ check_result() {
 	esac
 
 	if [ -s "$flist" ]; then
-		rc=0
 		diff -u "$flist" "$tmpdir"/flist ||
 			fatal "$TEST: file list FAIL"
 	else
-		cat "$tmpdir"/flist >"$flist"
+		message "$TEST: $flist: file list is not available"
+		cat >&2 "$tmpdir"/flist
+		fatal "$TEST: file list FAIL"
 	fi
 	message "$TEST: file list OK"
 }
