mki-pack-data: Return error if MKI_IMAGESUBDIR not found
Signed-off-by: Alexey Gladkov <legion@altlinux.org>

diff --git a/tools/mki-pack-data b/tools/mki-pack-data
--- a/tools/mki-pack-data
+++ b/tools/mki-pack-data
@@ -13,8 +13,13 @@ outname="${outname##*/}"
 cat >"$chroot/tmp/packimage.sh"<<EOF
 #!/bin/sh -efu
 imgdir=/.image
-[ -z "$imgsubdir" -o ! -d "/.image/$imgsubdir" ] ||
+if [ -n "$imgsubdir" ]; then
+	if [ ! -d "/.image/$imgsubdir" ]; then
+		printf '%s: %s: Directory not found\n' '$PROG' '/$imgsubdir' >&2
+		exit 1
+	fi
 	imgdir="/.image/$imgsubdir"
+fi
 cd /.our
 /.host/find -mindepth 1 -maxdepth 1 -exec rm -rf -- '{}' '+'
 [ -z '$outname' ] ||
