mki-pack-isoboot: Redirect messages to stderr
Signed-off-by: Alexey Gladkov <legion@altlinux.org>

diff --git a/tools/mki-pack-isoboot b/tools/mki-pack-isoboot
--- a/tools/mki-pack-isoboot
+++ b/tools/mki-pack-isoboot
@@ -27,13 +27,13 @@ cat >"$chroot/.host/packimage.sh"<<EOF
 #!/bin/sh -efu
 
 if [ ! -f /.image/syslinux/isolinux.bin ]; then
-	printf '%s\\n' "$PROG: /.image/syslinux/isolinux.bin: not found"
+	printf '%s\\n' "$PROG: /.image/syslinux/isolinux.bin: not found" >&2
 	exit 1
 fi
 
 if [ -n "${BOOT_LANG-}" ]; then
 	mkdir -p -- /.image/syslinux
-	printf '%s\n' "${BOOT_LANG-}" > /.image/syslinux/lang
+	printf '%s\\n' "${BOOT_LANG-}" > /.image/syslinux/lang
 fi
 
 cd /tmp
