mki-copy-efiboot-chrooted: Avoid using "type -t" in the posix code
Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>

diff --git a/tools/mki-copy-efiboot-chrooted b/tools/mki-copy-efiboot-chrooted
--- a/tools/mki-copy-efiboot-chrooted
+++ b/tools/mki-copy-efiboot-chrooted
@@ -327,7 +327,7 @@ refind_add_banner() {
 	[ -d "$gfxprefix" ] ||
 		return 0
 
-	type -t convert >&/dev/null ||
+	convert -version >/dev/null 2>&1 ||
 		return 0
 
 	bootlogo="`find "$gfxprefix" -name bootlogo | tail -1`"
@@ -488,11 +488,17 @@ img='.efiboot.img'
 dd if=/dev/zero of="$img" bs=32k count="$imgsize"
 
 # dosfstools-4.0 has dropped those ancient symlinks, *sigh*
-if type -t mkfs.fat >/dev/null; then
-	mkfs=mkfs.fat
-else
-	mkfs=mkfs.vfat
-fi
+mkfs=
+for bin in mkfs.fat mkfs.vfat; do
+	if $bin --help >/dev/null 2>&1; then
+		mkfs="$bin"
+		break
+	fi
+done
+
+[ -n "$mkfs" ] ||
+	fatal "Not found: mkfs.fat or mkfs.vfat"
+
 $mkfs $verbose -n "El Torito" $img
 
 # mtools insists that total number of sectors
