Almost all was rewritten, but with a same idea
Signed-off-by: Alexey Gladkov <legion@altlinux.org>

diff --git a/tools/mki-copy-pkgs b/tools/mki-copy-pkgs
--- a/tools/mki-copy-pkgs
+++ b/tools/mki-copy-pkgs
@@ -1,18 +1,15 @@
 #!/bin/ash -efu
 
-. shell-error
+. "${0%/*}"/mki-sh-functions
 
-verbose="${VERBOSE:+-v}"
-quiet="${QUIET:+-q}"
+verbose "has started executing."
+
 destdir="${MKI_DESTDIR:-}"
-NUMBER="${HSH_NUMBER:+--number="$HSH_NUMBER"}"
 REQUIRES="${MKI_REQUIRES:-}"
+aptboxdir="${PKGBOX:?global aptbox required}"
 
-aptboxdir="${APTBOXDIR:?global aptbox required}"
-dir="${WORKDIR:?workdir required}"
-
-ownership="$(stat -c '%u:%g' "$dir/chroot")" ||
-	fatal "$dir/chroot: Unable to get ownership"
+ownership="$(stat -c '%u:%g' "$chroot")" ||
+	fatal "$chroot: unable to get ownership."
 
 # assumed: defined aptbox
 APT_Get_PrintLocalFile=
@@ -89,37 +86,40 @@ $cached_uris" || local_uris="$cached_uris"
 		verbose 'calculated package file list.'
 }
 
-verbose "Work directory: $dir"
 if [ -z "$REQUIRES" ]; then
 	message "Nothing to do"
 	exit  0
 fi
 
-pkg_initlist=
-if [ -f "$REQUIRES" ]; then
-	pkg_init_list="$(grep -h '^[^#]' "$REQUIRES")" ||:
-else
-	pkg_init_list="$REQUIRES"
-fi
-
-printf '%s\n' "$pkg_init_list" |
+for r in $REQUIRES; do
+	if [ -f "$r" ]; then
+		grep -h '^[[:space:]]*[^#]' "$r" ||:
+	else
+		printf '%s\n' "$r"
+	fi |
 	tr ' ' '\n' |
-while read p; do
-	[ -n "$p" ] ||
-		continue
+	while read p; do
+		[ -n "$p" -a -n "${p##* *}" ] || continue
 
-	print_uris $p |
-		tr ' ' '\n' |
-		xargs -r cp $verbose -ut "$dir/chroot/.in/" -- ||
-	fatal 'Could not copy packages'
+		verbose "Copy packages for '$p'"
+		list="$(print_uris "$p")"
+
+		[ -n "$list" ] ||
+			fatal "$p: could not find package."
+
+		printf %s "$list" |
+			xargs -r cp $verbose -ut "$chroot/.in/" -- ||
+		fatal 'could not copy packages.'
+	done
 done
 
-cat > "$dir/chroot/tmp/script" <<EOF
+cat > "$chroot/tmp/script" <<EOF
 #!/bin/sh -efu
-rm -rf -- '/.subworkdir/$destdir'
-mkdir $verbose -p -- '/.subworkdir/$destdir'
-/.host/find /.in -mindepth 1 -maxdepth 1 |xargs -r cp $verbose -alt '/.subworkdir/$destdir' --
+mkdir $verbose -p -- '/.image/$destdir'
+exec /.host/find /.in -mindepth 1 -maxdepth 1 -execdir cp $verbose -alft '/.image/$destdir' -- '{}' '+'
 EOF
-chroot-exec "$dir/chroot/tmp/script"
+mki-exec "$chroot/tmp/script"
+rm -f -- "$chroot/tmp/script"
 
-find "$dir/chroot/.in/" -mindepth 1 -maxdepth 1 |xargs -r rm -rf --
+find "$chroot/.in/" -mindepth 1 -maxdepth 1 \
+	-execdir rm $verbose -rf -- '{}' '+'
