mki-copy-efiboot-chrooted: Reformat
Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>

diff --git a/tools/mki-copy-efiboot-chrooted b/tools/mki-copy-efiboot-chrooted
--- a/tools/mki-copy-efiboot-chrooted
+++ b/tools/mki-copy-efiboot-chrooted
@@ -8,13 +8,16 @@ EFI_BOOTARGS="${EFI_BOOTARGS-}"
 
 cd /.image
 
-fatal() { echo $*; exit 1; }
+fatal()
+{
+	echo $*
+	exit 1
+}
 
 stage2=
 for i in altinst live rescue; do
-	if [ -f "$i" ]; then
+	[ ! -f "$i" ] ||
 		stage2="${stage2:+$stage2 }$i"
-	fi
 done
 [ -n "${stage2:-}" ] ||
 	fatal "no stage2 image found."
@@ -37,19 +40,22 @@ else
 	bin_path="$boot/bootx64.efi"
 fi
 
-bootparams() {
-	[ -s "$1" ] || return 0
+bootparams()
+{
+	[ -s "$1" ] ||
+		return 0
 	stage2_size="$[ $(stat -c%s $1) / 1024 + 1 ]"
 	echo "ramdisk_size=$stage2_size stagename=$1"
 }
 
-shim_teen_path() {
+shim_teen_path()
+{
 	# find out if shim version is not less than 15
 	# looking at directory structure
 	# ia32 binaries should be present since that version
 	shim_dir_prefix="/usr/share/shim"
 	if [ -d "$shim_dir_prefix" ]; then
-		shim_max_version="$(find  $shim_dir_prefix -maxdepth 1 -type d | sed 's|\./||' | sort -n -r | head -1)"
+		shim_max_version="$(find  "$shim_dir_prefix" -maxdepth 1 -type d | sed 's|\./||' | sort -n -r | head -1)"
 		if [ ! "$shim_max_version" = "$shim_dir_prefix" ]; then
 			shimia32_dir="$shim_max_version/ia32"
 		else
@@ -58,30 +64,38 @@ shim_teen_path() {
 	fi
 }
 
-ia32efi_stack_full() {
+ia32efi_stack_full()
+{
 	# check if shim, refind and grub-efi include ia32 EFI binaries
 	# if signed shim is absent try to fallback to unsigned one
 	[ -f "$efi_bindir/shimia32.efi" ] || shim_teen_path
 	[ -f "$efi_bindir/refind_ia32.efi" ] || ia32efi_flag="absent"
 	[ -f "$efi_bindir/grubia32.efi" ] || ia32efi_flag="absent"
 
-	[ "$ia32efi_flag" != "absent" ] ||
-		echo "Warning! Some of required bootloader packages in current branch miss ia32 binaries, ia32 EFI support is therefore disabled."
-
+	if [ "$ia32efi_flag" = "absent" ]; then
+		printf '%s' \
+			"Warning! " \
+			"Some of required bootloader packages in current branch " \
+			"miss ia32 binaries, ia32 EFI support is therefore disabled."
+		printf '\n'
+	fi
 }
 
 efi_bindir=/usr/lib64/efi
 
-copy_shell() {
+copy_shell()
+{
 	dest="$efi/$shell"
 	src="$efi_bindir/shell.efi"
 	[ ! -f "$src" ] ||
 		cp $verbose -pLf "$src" "$dest"
 }
 
-copy_mt86() {
+copy_mt86()
+{
 	dest="$tools"
 	mkdir $verbose -p "$dest"
+
 	src="$efi_bindir/memtest86.efi"
 	if [ -f "$src" ]; then
 		cp $verbose -pLf "$src" "$dest/memtest86.efi" &&
@@ -90,20 +104,22 @@ copy_mt86() {
 	fi
 }
 
-purge_mt86() {
+purge_mt86()
+{
 	(
-	cd "$tools" ||
-		return 0
+		cd "$tools" ||
+			exit 0
 
-	if [ -s memtest86.efi ]; then
-		rm $verbose -f memtest86.efi
-		find /usr/share/efi-memtest86 -type f -printf '%f\n' |
-			xargs rm $verbose -f
-	fi
+		if [ -s memtest86.efi ]; then
+			rm $verbose -f memtest86.efi
+			find /usr/share/efi-memtest86 -type f -printf '%f\n' |
+				xargs rm $verbose -f
+		fi
 	)
 }
 
-copy_cert() {
+copy_cert()
+{
 	[ -n "$EFI_CERT" ] ||
 		return 0
 
@@ -115,7 +131,8 @@ copy_cert() {
 	cp $verbose -pLft "$cert" -- "$keyfile"
 }
 
-copy_shim() {
+copy_shim()
+{
 	[ -n "${shim_path:-}" ] ||
 		return 0
 	copy_cert
@@ -144,7 +161,8 @@ copy_shim() {
 	fi
 }
 
-copy_kernel() {
+copy_kernel()
+{
 	[ ! -s "$boot/vmlinuz" ] && [ ! -s "$boot/full.cz" ] ||
 		return 0
 
@@ -153,7 +171,8 @@ copy_kernel() {
 
 kargs="fastboot live lowmem showopts automatic=method:cdrom $EFI_BOOTARGS"
 
-copy_elilo() {
+copy_elilo()
+{
 	cp $verbose -pLf "$efi_bindir/elilo.efi" "${1:-$bin_path}"
 	cat > "$boot/elilo.conf" <<- ELILO_EOF
 	append="$kargs"
@@ -167,15 +186,20 @@ copy_elilo() {
 			>> "$boot/elilo.conf"
 }
 
-copy_grub() {
-
+copy_grub()
+{
 	cp $verbose -pLf "$efi_bindir/grubx64.efi" "$boot/grubx64.efi"
 	cp $verbose -pLf "$efi_bindir/grubia32.efi" "$boot/grubia32.efi"
-	[ -d "$boot/fonts" ] || mkdir $verbose -p "$boot/fonts"
+
+	[ -d "$boot/fonts" ] ||
+		mkdir $verbose -p "$boot/fonts"
+
 	cp $verbose -arf /usr/lib64/grub/x86_64-efi "$boot"
 	cp $verbose -arf /usr/lib64/grub/i386-efi "$boot/"
+
 	find "$boot/x86_64-efi" -type f -name '*.module' -delete ||:
 	find "$boot/i386-efi" -type f -name '*.module' -delete ||:
+
 	cp $verbose -Lf /boot/grub/fonts/unicode.pf2 "$boot/fonts"
 	cp $verbose -Lf /boot/grub/unifont.pf2 "$boot"
 
@@ -183,7 +207,8 @@ copy_grub() {
 }
 
 
-add_langs() {
+add_langs()
+{
 	cat <<- REFIND_EOF
 	  submenuentry "English" {
 	    add_options "lang=en_US"
@@ -200,12 +225,17 @@ add_langs() {
 	REFIND_EOF
 }
 
-add_forensic_mode() {
-	[ -f rescue ] || return 0
+add_forensic_mode()
+{
+	[ -f rescue ] ||
+		return 0
+
 	forensic_args="$(sed -rn \
 		's,^.* stagename=rescue (.*forensic hash=[0-9a-f]+)$,\1,p' \
 		syslinux/isolinux.cfg)"
-	[ -n "$forensic_args" ] || return 0
+
+	[ -n "$forensic_args" ] ||
+		return 0
 
 	cat <<- REFIND_EOF
 	  submenuentry "Forensic mode (leave disks alone)" {
@@ -216,55 +246,63 @@ add_forensic_mode() {
 
 add_stage2() {
 	count="`echo $stage2 | wc -w`"
+
 	for root in $stage2; do
 		case "$root" in
-		altinst)
-			splash="splash "
-			label="Installation";;
-		live)
-			splash="splash "
-			label="Live";;
-		rescue)
-			splash=
-			label="Rescue";;
-		*)
-			label="$root";;
+			altinst)
+				splash="splash "
+				label="Installation"
+				;;
+			live)
+				splash="splash "
+				label="Live"
+				;;
+			rescue)
+				splash=
+				label="Rescue"
+				;;
+			*)
+				label="$root"
+				;;
 		esac
 
 		# provide differentiating boot target icons if needed
 		icon="$refind_icons/altlinux/$root.$icon_format"
+
 		[ "$count" -ne 1 ] && [ -s "$icon" ] ||
 			icon="$refind_icons/os_altlinux.$icon_format"
 
-
 		case "$1" in
-		x64)
-			cat <<- REFIND_EOF
+			x64)
+				cat <<- REFIND_EOF
 
-			# ELILO used as SB trampoline for unsigned kernels
-			menuentry "ALT Linux $label" {
-			  icon /$icon
-			  loader /$boot/elilo.efi
-			  # NB: -v seems critical, otherwise we hit this:
-			  #     gzip_x86_64: invalid exec_header
-			  options "-v -i full.cz vmlinuz `bootparams $root` $splash"
-			REFIND_EOF
-			[ "$root" = rescue ] && add_forensic_mode || add_langs
-			echo "}";;
-		ia32)
-			cat <<- REFIND_EOF
+				# ELILO used as SB trampoline for unsigned kernels
+				menuentry "ALT Linux $label" {
+				  icon /$icon
+				  loader /$boot/elilo.efi
+				  # NB: -v seems critical, otherwise we hit this:
+				  #     gzip_x86_64: invalid exec_header
+				  options "-v -i full.cz vmlinuz `bootparams $root` $splash"
+				REFIND_EOF
+				[ "$root" = rescue ] && add_forensic_mode || add_langs
+				echo "}"
+				;;
+			ia32)
+				cat <<- REFIND_EOF
 
-			# GRUB-EFI is used as SB trampoline for unsigned kernels
-			# for ia32 EFI on x86_64 platforms
-			  menuentry "ALT Linux $label" {
-			  icon /$icon
-			  loader /$boot/grubia32_ldr.efi
-			  options ""
-			REFIND_EOF
-			[ "$root" = rescue ] && add_forensic_mode || add_langs
-			echo "}";;
-		*)
-			fatal "Unknown architecture argument '$1' in add_stage2()!";;
+				# GRUB-EFI is used as SB trampoline for unsigned kernels
+				# for ia32 EFI on x86_64 platforms
+				  menuentry "ALT Linux $label" {
+				  icon /$icon
+				  loader /$boot/grubia32_ldr.efi
+				  options ""
+				REFIND_EOF
+				[ "$root" = rescue ] && add_forensic_mode || add_langs
+				echo "}"
+				;;
+			*)
+				fatal "Unknown architecture argument '$1' in add_stage2()!"
+				;;
 		esac
 	done
 }
@@ -273,12 +311,19 @@ gfxprefix=/usr/share/gfxboot
 
 add_banner() {
 	local bgfile="$refind_icons/bg.png"
-	[ -d "$gfxprefix" ] || return 0
-	type -t convert >&/dev/null || return 0
+
+	[ -d "$gfxprefix" ] ||
+		return 0
+
+	type -t convert >&/dev/null ||
+		return 0
+
 	bootlogo="`find "$gfxprefix" -name bootlogo | tail -1`"
-	[ -s "$bootlogo" ] || return 0
-	if [ -s "$bgfile" ] || cpio -i --quiet --to-stdout back.jpg \
-		< "$bootlogo" | convert - "$bgfile"; then
+
+	[ -s "$bootlogo" ] ||
+		return 0
+
+	if [ -s "$bgfile" ] || cpio -i --quiet --to-stdout back.jpg < "$bootlogo" | convert - "$bgfile"; then
 		echo "banner /$bgfile"
 	fi
 }
@@ -318,7 +363,8 @@ scan_icon=os_unknown."$icon_format"
 # http://www.rodsbooks.com/refind/configfile.html
 blacklist="shim.efi shimx64.efi shimia32.efi shim-fedora.efi PreLoader.efi TextMode.efi ebounce.efi GraphicsConsole.efi MokManager.efi mmx64.efi mmia32.efi HashTool.efi HashTool-signed.efi elilo.efi"
 
-copy_refind() {
+copy_refind()
+{
 	copy_elilo "$boot/elilo.efi"
 
 	mkdir $verbose -p "$boot" "$refind_aux"
@@ -340,15 +386,14 @@ copy_refind() {
 
 	mkdir $verbose -p "$boot/icons"
 	find "$refind_icons/" \
-		-name 'func_*' -o -name 'tool_*' -o -name 'vol_*' \
-		-o -name "$scan_icon" |
+		-name 'func_*' -o -name 'tool_*' -o -name 'vol_*' -o -name "$scan_icon" |
 		xargs -r cp $verbose -lpft "$boot/icons"
 
 	[ ! -d "$refind_aux/altlinux" ] ||
 		mv "$refind_aux/altlinux" "$boot/icons"
 
 	# empty aux refind configuration makes it scan for loaders
-		refind_autodetect > "$refind_aux/refind.conf"
+	refind_autodetect > "$refind_aux/refind.conf"
 
 	#if ia32 EFI bootloader stack is full
 	if [ "$ia32efi_flag" = "present" ]; then
@@ -412,14 +457,18 @@ ia32efi_stack_full
 	copy_shim
 
 case "$EFI_BOOTLOADER" in
-elilo)
-	copy_elilo;;
-refind)
-	copy_refind;;
-grub-efi)
-	copy_grub;;
-*)
-	fatal "Unable to handle '$EFI_BOOTLOADER'.";;
+	elilo)
+		copy_elilo
+		;;
+	refind)
+		copy_refind
+		;;
+	grub-efi)
+		copy_grub
+		;;
+	*)
+		fatal "Unable to handle '$EFI_BOOTLOADER'."
+		;;
 esac
 
 copy_kernel	# seems to be unavoidable
@@ -427,7 +476,7 @@ copy_shell
 copy_mt86
 
 imgsize="$[ $(du -lsB32k $efi | cut -f1) + 10 ]"
-img=.efiboot.img
+img='.efiboot.img'
 
 dd if=/dev/zero of="$img" bs=32k count="$imgsize"
 
