hsh_initroot: Put workdir into separate variable
Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>

diff --git a/tools/mki-sh-image-prepare b/tools/mki-sh-image-prepare
--- a/tools/mki-sh-image-prepare
+++ b/tools/mki-sh-image-prepare
@@ -16,6 +16,8 @@ apt_config="${HSH_APT_CONFIG:+--apt-config="$HSH_APT_CONFIG"}"
 apt_prefix="${HSH_APT_PREFIX:+--apt-prefix="$HSH_APT_PREFIX"}"
 
 hsh_initroot() {
+	local wdir="$1"; shift
+
 	env -i PATH="$PATH" \
 	hsh \
 		--initroot \
@@ -28,8 +30,8 @@ hsh_initroot() {
 		${HSH_EXCLUDE_DOCS:+--excludedocs} \
 		${HSH_CACHEDIR:+--cache-dir="$HSH_CACHEDIR"} \
 		${IMAGE_INIT_LIST:+--pkg-init-list="$IMAGE_INIT_LIST"} \
-		-- "$1" ||
-	fatal "$1: unable to make initial chroot: rc=$?"
+		-- "$wdir" ||
+	fatal "$wdir: unable to make initial chroot: rc=$?"
 
 	local pkgs="${PACKAGES_REQUIRED_INITROOT:-}"
 	if [ -n "$pkgs" ]; then
@@ -38,23 +40,23 @@ hsh_initroot() {
 			$verbose $quiet \
 			${HSH_NUMBER:+--number="$HSH_NUMBER"} \
 			${HSH_EXCLUDE_DOCS:+--excludedocs} \
-			-- "$1" $pkgs ||
-		fatal "$1: unable to install packages: rc=$?"
+			-- "$wdir" $pkgs ||
+		fatal "$wdir: unable to install packages: rc=$?"
 	fi
 
 	# Create missing objects in hasher root's /dev.
-	[ -d "$1"/chroot/dev/shm ] ||
-		install -d -m1777 "$1"/chroot/dev/shm
-	[ -d "$1"/chroot/dev/pts ] ||
-		install -d -m755 "$1"/chroot/dev/pts
-	[ -L "$1"/chroot/dev/fd ] ||
-		ln -s /proc/self/fd "$1"/chroot/dev/fd
-	[ -L "$1"/chroot/dev/stdin ] ||
-		ln -s /proc/self/fd/0 "$1"/chroot/dev/stdin
-	[ -L "$1"/chroot/dev/stdout ] ||
-		ln -s /proc/self/fd/1 "$1"/chroot/dev/stdout
-	[ -L "$1"/chroot/dev/stderr ] ||
-		ln -s /proc/self/fd/2 "$1"/chroot/dev/stderr
+	[ -d "$wdir"/chroot/dev/shm ] ||
+		install -d -m1777 "$wdir"/chroot/dev/shm
+	[ -d "$wdir"/chroot/dev/pts ] ||
+		install -d -m755 "$wdir"/chroot/dev/pts
+	[ -L "$wdir"/chroot/dev/fd ] ||
+		ln -s /proc/self/fd "$wdir"/chroot/dev/fd
+	[ -L "$wdir"/chroot/dev/stdin ] ||
+		ln -s /proc/self/fd/0 "$wdir"/chroot/dev/stdin
+	[ -L "$wdir"/chroot/dev/stdout ] ||
+		ln -s /proc/self/fd/1 "$wdir"/chroot/dev/stdout
+	[ -L "$wdir"/chroot/dev/stderr ] ||
+		ln -s /proc/self/fd/2 "$wdir"/chroot/dev/stderr
 
 	printf "%s\n" \
 		"666 /dev/null c 1 3" \
@@ -67,20 +69,20 @@ hsh_initroot() {
 		"666 /dev/tty c 5 0" \
 		"666 /dev/ptmx c 5 2" |
 	while read mode name type major minor ; do
-		[ ! -e "$1/chroot/$name" ] ||
+		[ ! -e "$wdir/chroot/$name" ] ||
 			continue
 		mki-fakedev \
 			$verbose $quiet \
 			-o root \
 			-m "$mode" \
-			-- "$1" "$name" "$type" "$major" "$minor" ||
+			-- "$wdir" "$name" "$type" "$major" "$minor" ||
 		fatal 'Failed to create essential devices.'
 	done
 
-	if [ ! -e "$1"/chroot/dev/pts/ptmx ]; then
-		mv "$1"/chroot/dev/ptmx "$1"/chroot/dev/pts/ptmx
-		ln -s pts/ptmx "$1"/chroot/dev/ptmx
+	if [ ! -e "$wdir"/chroot/dev/pts/ptmx ]; then
+		mv "$wdir"/chroot/dev/ptmx "$wdir"/chroot/dev/pts/ptmx
+		ln -s pts/ptmx "$wdir"/chroot/dev/ptmx
 	fi
 
-	rm -rf -- "$1/repo" "$1/chroot/.out"
+	rm -rf -- "$wdir/repo" "$wdir/chroot/.out"
 }
